import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { FaReact } from "react-icons/fa";
import { LuGraduationCap } from "react-icons/lu";

export const links = [
  {
    name: "Home",
    hash: "#home",
  },
  {
    name: "About",
    hash: "#about",
  },
  {
    name: "Projects",
    hash: "#projects",
  },
  {
    name: "Skills",
    hash: "#skills",
  },
  {
    name: "Experience",
    hash: "#experience",
  },
  {
    name: "Contact",
    hash: "#contact",
  },
] as const;

export const experiencesData = [
  {
    title: "Bachelor of Engineering, Computer Engineering",
    location: "Kakinada Institute of Engineering and Technology, India",
    description:
      "Earned a Bachelor of Engineering in Computer Engineering with a GPA of 3.58/4.00, establishing a strong foundation in software engineering principles, data structures, and full stack web development.",
    icon: React.createElement(LuGraduationCap),
    date: "Mar 2020",
    level: "Foundation",
    technologies: ["HTML", "CSS", "JavaScript", "Python", "MySQL", "Database Design"],
  },
  {
    title: "Software Developer",
    location: "Multiplier AI Solutions, Hyderabad, India",
    description:
      "Redesigned and optimized 15+ healthcare staff-facing workflow screens for responsive desktop and tablet usage using React.js, Next.js, Tailwind CSS, CSS Grid, and Flexbox. Debugged complex UI issues across high-interaction flows by tracing component state, event handlers, and API behavior, then applied debouncing, throttling, and state optimization to improve responsiveness by 20%. Built pixel-perfect React components from Figma and followed strong PR and code-review standards for reliable delivery.",
    icon: React.createElement(CgWorkAlt),
    date: "Apr 2020 - Jan 2022",
    level: "Entry Level",
    technologies: [
      "React",
      "Next.js",
      "JavaScript",
      "Python",
      "Tailwind CSS",
      "Node.js",
      "REST APIs",
      "Responsive Design",
      "Figma",
      "Git",
    ],
  },
  {
    title: "Software Developer",
    location: "Rapid Innovation, Noida, India",
    description:
      "Owned React frontend services across routing, data models, and large dataset pipelines serving 20K+ records per request. Built full-stack features for a financial analytics platform using React.js, TypeScript, Node.js, GraphQL, PostgreSQL, and Redis, delivering 25+ dashboards with drilldowns, complex filters, and aggregations. Improved performance by 35% by profiling React rendering, using RTK Query caching, lazy loading, and code splitting. Implemented JWT/OAuth2 authentication and RBAC-based rendering, and established Jenkins CI/CD with Jest and React Testing Library for stable releases.",
    icon: React.createElement(CgWorkAlt),
    date: "Feb 2022 - Jun 2023",
    level: "Mid Level",
    technologies: [
      "React",
      "TypeScript",
      "Node.js",
      "GraphQL",
      "Redux Toolkit",
      "PostgreSQL",
      "Redis",
      "JWT",
      "OAuth2",
      "RBAC",
      "Terraform",
      "Jenkins",
      "Jest",
      "React Testing Library",
      "Git",
    ],
  },
  {
    title: "Senior Software Developer",
    location: "Perky (Perspective Partners LLC), New York, NY",
    description:
      "Led frontend architecture for enterprise SaaS platforms using Next.js App Router, Server Components, and SSR, delivering scalable React systems, reusable component libraries, and AI-integrated UIs across financial and HR products. Built shared React + TypeScript UI patterns for forms, multi-step workflows, tables, and modals with Redux Toolkit, RTK Query, Zod, and React Hook Form, reducing average dashboard data fetch latency from 800ms to under 200ms. Architected an AI leave-policy assistant using LangGraph and FastAPI with vector retrieval workflows for document grounding and response generation. Improved data-heavy dashboard performance by 35% through render optimization, code splitting, and caching, while driving CI/CD, code-review standards, and cross-functional Agile delivery.",
    icon: React.createElement(FaReact),
    date: "Mar 2024 - Present",
    level: "Senior",
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "Python",
      "FastAPI",
      "Redux Toolkit",
      "RTK Query",
      "Tailwind CSS",
      "Zod",
      "React Hook Form",
      "Storybook",
      "Micro Frontends",
      "PostgreSQL",
      "Redis",
      "LangGraph",
      "RAG",
      "MCP",
      "Vector DB",
      "Vercel AI SDK UI",
      "AWS",
      "Docker",
      "Jenkins",
    ],
  },
  {
    title: "Master of Science, Computer Science",
    location: "Avila University, Kansas, USA",
    description:
      "Completed graduate study focused on advanced algorithms, machine learning, and AI systems with a strong academic record (GPA 3.63/4.00).",
    icon: React.createElement(LuGraduationCap),
    date: "Dec 2024",
    level: "Advanced",
    technologies: ["Algorithms", "Machine Learning", "AI Systems", "Research"],
  },
] as const;

export const projectsData = [
  {
    title: "HR Management Web Platform",
    description:
      "HR and benefits platform where employees and managers handle leave balances, benefits visibility, and approval workflows through role-based dashboards. Built a React + Next.js multi-tenant UI with strict access controls, audit trails, server-side pagination, and cross-filter synchronization for finance and admin teams. Implemented an AI leave-policy assistant using LangGraph + FastAPI with vector retrieval and grounding workflows to deliver accurate policy answers. Deployed on AWS with Dockerized CI/CD across three environments for consistent releases.",
    tags: [
      "React.js",
      "Next.js",
      "TypeScript",
      "Node.js",
      "Python",
      "FastAPI",
      "LangGraph",
      "RAG",
      "Vector DB",
      "RTK Query",
      "Tailwind CSS",
      "RBAC",
      "AWS",
      "Docker",
      "PostgreSQL",
      "Redis",
    ],
  },
  {
    title: "AI Leave Policy Assistant",
    description:
      "Enterprise AI assistant built for HR workflows to answer leave-policy questions using trustworthy retrieval rather than generic responses. Designed multi-step LangGraph agent workflows for document retrieval, context ranking, and final response generation through FastAPI services and vector embeddings. Integrated with role-based enterprise UI flows so employees receive grounded answers inside existing React dashboard experiences. Focused on latency, response quality, and maintainability for production-ready GenAI behavior.",
    tags: [
      "React.js",
      "TypeScript",
      "Next.js",
      "FastAPI",
      "LangGraph",
      "RAG",
      "Vector DB",
      "MCP",
      "Vercel AI SDK UI",
      "AWS",
      "Python",
    ],
  },
  {
    title: "Financial Analytics Web Application",
    description:
      "Reporting platform for finance and business teams to track metrics, run drilldowns, and generate reports across large datasets in real time. Built 25+ React + TypeScript dashboards through a centralized component system, enabling reusable chart, table, and filter patterns across teams. Used Redis caching and optimized data pipelines to reduce load times from 8 seconds to under 2 seconds under heavy usage. Added Datadog instrumentation and CI/CD automation to improve reliability and release predictability.",
    tags: [
      "React.js",
      "TypeScript",
      "Node.js",
      "PostgreSQL",
      "Redis",
      "Redux Toolkit",
      "GraphQL",
      "Datadog",
      "Jenkins",
      "AWS",
      "Terraform",
    ],
  },
  {
    title: "Medicine E-Commerce Platform",
    description:
      "Online medicine selling platform where customers could browse, search, and purchase medicines with real-time inventory tracking and secure checkout. Integrated Stripe for end-to-end payment processing including one-time purchases and prescription-based order flows. Deployed on AWS with S3 for product image storage, RDS for order and inventory data, and EC2 for compute, handling reliable transactions at scale across a growing user base.",
    tags: [
      "React.js",
      "Python",
      "Django",
      "Stripe",
      "AWS",
      "PostgreSQL",
      "REST APIs",
      "S3",
      "EC2",
      "RDS",
    ],
  },
] as const;

export const skillsData = [
  "React.js",
  "Next.js",
  "Next.js (App Router, SSR/SSG)",
  "TypeScript",
  "JavaScript (ES6+)",
  "Redux Toolkit",
  "RTK Query",
  "React Hooks",
  "Context API",
  "Micro Frontend",
  "Storybook",
  "Tailwind CSS",
  "Sass",
  "HTML5",
  "CSS3",
  "WCAG 2.1 Accessibility",
  "Responsive Design",
  "Python",
  "Node.js",
  "Express.js",
  "FastAPI",
  "REST APIs",
  "GraphQL",
  "Apollo",
  "Terraform",
  "JWT Authentication",
  "RBAC",
  "RAG",
  "Agentic AI",
  "LangGraph",
  "Vercel AI SDK UI",
  "MCP",
  "Vector DB",
  "Retrieval Grounding",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "SQL Server",
  "Jest",
  "React Testing Library",
  "Integration Testing",
  "Regression Testing",
  "Unit Testing",
  "Jenkins",
  "GitHub Actions",
  "Docker",
  "AWS",
  "Webpack",
  "Vite",
  "SonarQube",
  "New Relic",
  "Git",
  "Structured Logging",
] as const;
