import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { FaReact } from "react-icons/fa";
import { LuGraduationCap } from "react-icons/lu";

export const links = [
  { name: "Home", hash: "#home" },
  { name: "About", hash: "#about" },
  { name: "Projects", hash: "#projects" },
  { name: "Skills", hash: "#skills" },
  { name: "Experience", hash: "#experience" },
  { name: "Contact", hash: "#contact" },
] as const;

export const experiencesData = [
  {
    title: "Bachelor of Engineering, Computer Engineering",
    location: "Kakinada Institute of Engineering and Technology, India",
    description:
      "Graduated with a GPA of 3.58/4.00, building a solid foundation in software engineering, data structures, and full stack web development that shaped my approach to building systems from the ground up.",
    icon: React.createElement(LuGraduationCap),
    date: "Mar 2020",
    level: "Foundation",
    technologies: ["HTML", "CSS", "JavaScript", "Python", "MySQL", "Database Design"],
  },
  {
    title: "Software Developer",
    location: "Multiplier AI Solutions | Client: Apollo Hospitals, Hyderabad, India",
    description:
      "Configured GitHub Actions CI/CD pipelines with Docker containerization and Datadog APM instrumentation for Apollo Hospitals' healthcare platform, cutting deployment time by 40% and improving production incident visibility across environments. Engineered an event-driven notification queue system with RBAC that enabled role-based alert routing across automated workflows. Built React and TypeScript UI modules for staff-facing screens, applying debouncing, throttling, and component-level profiling to improve screen responsiveness by 20%.",
    icon: React.createElement(CgWorkAlt),
    date: "Apr 2020 - Jan 2022",
    level: "Entry Level",
    technologies: [
      "React",
      "TypeScript",
      "JavaScript",
      "Python",
      "Tailwind CSS",
      "REST APIs",
      "Docker",
      "GitHub Actions",
      "Datadog",
      "RBAC",
      "Git",
    ],
  },
  {
    title: "Software Developer",
    location: "Rapid Innovation | Client: ICICI Home Finance, Noida, India",
    description:
      "Engineered RESTful and GraphQL APIs using Python Django secured with OAuth 2.0, powering financial analytics dashboards for ICICI Home Finance's loan portfolio platform. Containerized the full stack with multi-stage Docker builds across development, staging, and production environments, cutting mean deployment time from 6 hours to under 45 minutes. Optimized PostgreSQL execution plans and Redis cache strategies, improving platform performance by 35% and reducing dashboard load from 8 seconds to 2 seconds. Enforced TDD with pytest across API contracts, ORM queries, and serializers to maintain high test coverage.",
    icon: React.createElement(CgWorkAlt),
    date: "Feb 2022 - Jun 2023",
    level: "Mid Level",
    technologies: [
      "Python",
      "Django",
      "GraphQL",
      "React",
      "TypeScript",
      "PostgreSQL",
      "Redis",
      "Docker",
      "OAuth2",
      "pytest",
      "Git",
    ],
  },
  {
    title: "Senior AI Engineer",
    location: "Perky (Perspective Partners LLC) | Client: Lincoln Financial Group, New York, NY",
    description:
      "Built end-to-end full stack features for Lincoln Financial Group's financial analytics platform using React, TypeScript, Python Django, and GraphQL, delivering 25+ data-intensive dashboards with complex filtering, drilldown navigation, and real-time aggregations. Managed Kubernetes deployments on AWS EKS with rolling updates, pod autoscaling, and health probes, maintaining 99.9% uptime across containerized services handling 20K+ records per request. Engineered Python REST API services with RBAC, JWT/OAuth enforcement, and audit logging for enterprise API governance. Containerized with Docker, deployed to AWS, and automated GitLab CI/CD pipelines achieving 40% faster release cycles. Leveraged GitHub Copilot and Claude AI to accelerate feature delivery while consistently reviewing and refining AI-generated code.",
    icon: React.createElement(FaReact),
    date: "Mar 2024 - Present",
    level: "Senior",
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Python",
      "Django",
      "FastAPI",
      "GraphQL",
      "LangGraph",
      "RAG",
      "PostgreSQL",
      "Redis",
      "Kubernetes",
      "Docker",
      "AWS",
      "GitLab CI/CD",
      "JWT",
      "RBAC",
    ],
  },
  {
    title: "Master of Science, Computer Science",
    location: "Avila University, Kansas, USA",
    description:
      "Completed graduate study focused on advanced algorithms, machine learning, and AI systems with a strong academic record (GPA 3.63/4.00).",
    icon: React.createElement(LuGraduationCap),
    date: "Dec 2024",
    level: "Advanced",
    technologies: ["Algorithms", "Machine Learning", "AI Systems", "Research"],
  },
] as const;

export const projectsData = [
  {
    title: "HR Management Platform",
    description:
      "Enterprise HR benefits platform built for Lincoln Financial Group where employees and managers handle leave balances, benefits visibility, and approval workflows through role-based dashboards. Features an LLM-powered policy assistant built with LangGraph and FastAPI that enables employee self-service query resolution using vector retrieval and document grounding. Designed for multi-tenant scale with RBAC enforcement, full audit trails, notifications, and compliance-grade workflows deployed across three AWS environments.",
    tags: [
      "React.js",
      "Next.js",
      "TypeScript",
      "Python",
      "FastAPI",
      "LangGraph",
      "RAG",
      "Vector DB",
      "PostgreSQL",
      "Redis",
      "RBAC",
      "AWS",
      "Docker",
      "Kubernetes",
    ],
  },
  {
    title: "AI Leave Policy Assistant",
    description:
      "Conversational AI assistant built for Lincoln Financial Group's HR workflows that answers leave-policy questions using retrieval-augmented generation rather than generic responses. Designed multi-step LangGraph agent workflows for document retrieval, context ranking, and response generation through FastAPI services and vector embeddings. Integrated into the existing React dashboard so employees get grounded policy answers without leaving their workflow. Focused on response accuracy, latency, and maintainability to meet production-grade GenAI standards.",
    tags: [
      "React.js",
      "TypeScript",
      "Next.js",
      "FastAPI",
      "LangGraph",
      "RAG",
      "Vector DB",
      "MCP",
      "AWS Bedrock",
      "Python",
    ],
  },
  {
    title: "Financial Analytics Platform",
    description:
      "Real-time financial analytics platform built for ICICI Home Finance to monitor loan portfolio performance across 25+ dashboards with automated document processing workflows. Served as the primary backend engineer owning API development, query performance tuning, and delivery pipeline setup. Optimized PostgreSQL execution plans and Redis caching strategies, reducing dashboard load time by 75% and eliminating manual reporting bottlenecks for analyst teams. Added Datadog instrumentation and GitLab CI/CD automation to improve release predictability.",
    tags: [
      "Python",
      "Django",
      "React.js",
      "TypeScript",
      "PostgreSQL",
      "Redis",
      "GraphQL",
      "Docker",
      "Datadog",
      "AWS",
      "GitLab CI/CD",
    ],
  },
  {
    title: "Medicine E-Commerce Platform",
    description:
      "Online medicine platform where customers browse, search, and purchase medicines with real-time inventory tracking and secure checkout. Integrated Stripe for end-to-end payment processing covering one-time purchases and prescription-based order flows. Deployed on AWS with S3 for product image storage, RDS for order and inventory data, and EC2 for compute, handling reliable transactions at scale.",
    tags: [
      "React.js",
      "Python",
      "Django",
      "Stripe",
      "AWS",
      "PostgreSQL",
      "REST APIs",
      "S3",
      "EC2",
      "RDS",
    ],
  },
] as const;

export const aiProjectsData = [
  {
    id: 1,
    title: "N8N AI Job Application Automation",
    badge: "Featured",
    categoryLabel: "AI Automation / No-Code / LLM",
    description:
      "An end-to-end AI-powered job application system built entirely in n8n. Uses Apify to scrape fresh job listings, feeds them into an OpenAI AI Agent acting as a Resume Analyst, which rewrites and tailors the resume and cover letter to match each job description with ATS-optimized keywords. The tailored content is injected into a Google Docs template to generate a polished PDF. AnyMail Finder locates the hiring manager's direct email, and a personalized Gmail is sent with the custom resume attached, bypassing the job portal black hole entirely. Dramatically increases application volume while maintaining high personalization at scale.",
    tags: ["n8n", "OpenAI AI Agent", "Apify", "AnyMail Finder", "Google Docs API", "Gmail API", "LLM", "Automation", "ATS Optimization"],
    loomVideoId: "307dcaacea764e27adb833559e86c6a9",
    loomNote: null,
    githubUrl: null,
  },
  {
    id: 2,
    title: "NVIDIA Medical Advice RAG",
    badge: "NVIDIA Contest Winner 2024",
    categoryLabel: "RAG Pipeline",
    description:
      "A medical RAG system built for the NVIDIA Developer Contest using NVIDIA's NV-Embed-QA embedding model and LlamaIndex. Users enter health symptoms and the system retrieves contextually accurate medical insights by embedding documents with NVIDIA embeddings and organizing them via LlamaIndex for fast retrieval. Answers are generated through an intuitive Streamlit interface. Submitted to and recognized by the NVIDIA AI Developer Contest. Makes medical information accessible, precise, and grounded with no hallucinations.",
    tags: ["NVIDIA AI Endpoints", "NV-Embed-QA", "LlamaIndex", "Streamlit", "Python", "RAG", "HuggingFace", "Vector Embeddings"],
    loomVideoId: "61c10718fc19472cae6b2b49486c9f84",
    loomNote: null,
    githubUrl: "https://github.com/saiMahadasa/llamaindex_nvidia_medical_advice_rag",
  },
  {
    id: 3,
    title: "Medical Assistant RAG Chatbot",
    badge: "RAG Pipeline",
    categoryLabel: "RAG Pipeline",
    description:
      "An AI-powered Medical Assistant Chatbot trained on a 600+ page medical book PDF. Uses LangChain, Sentence Transformers, and Pinecone vector database to deliver accurate, context-driven answers. Every response is grounded in the trained document with no hallucinations. Features vector embeddings for precise retrieval, a custom interactive chat UI built with HTML, CSS, and JavaScript, and a Flask backend serving the OpenAI-powered RAG chain. Fully open-sourced on GitHub.",
    tags: ["LangChain", "OpenAI GPT", "Pinecone", "Sentence Transformers", "Flask", "Python", "HTML/CSS/JS", "RAG"],
    loomVideoId: "a83bb0b5851f49f2b3f83f60aa2d19a4",
    loomNote: null,
    githubUrl: "https://github.com/saiMahadasa/medical_chatbot",
  },
  {
    id: 4,
    title: "AI Portfolio Chatbot",
    badge: "Live in Production",
    categoryLabel: "Deployed",
    description:
      "A deployed, production-grade AI assistant integrated into this portfolio. Built with LangChain and OpenAI GPT-3.5-turbo-instruct, it answers questions about my career, projects, and skills using a custom persona-locked prompt with scope guardrails to prevent off-topic responses. Temperature set to 0 for professional consistency. Flask backend with CORS enabled, deployed via Procfile, integrated with the React frontend. This is the chatbot visible on this site right now.",
    tags: ["LangChain", "OpenAI GPT", "Flask", "React", "CORS", "Python", "Deployed", "Procfile"],
    loomVideoId: null,
    loomNote: "This is the AI assistant running live on this site. Try it using the chat button in the bottom-right corner.",
    githubUrl: "https://github.com/saiMahadasa/ai_portfolio_chatbot",
  },
  {
    id: 5,
    title: "Financial Stock Advisor AI",
    badge: "Structured Output",
    categoryLabel: "OpenAI API / NLP",
    description:
      "Built with React.js and the OpenAI API, this app uses LLM-powered NLP to predict stock prices and surface estimated returns for investors in real time. Microsoft Copilot Studio handles the conversational layer, letting users query company performance through natural language and receive AI-generated profitability signals without needing financial expertise. The OpenAI model processes market-relevant inputs to deliver structured, actionable outputs through a clean, responsive interface across desktop and mobile.",
    tags: ["React.js", "OpenAI API", "Microsoft Copilot Studio", "LLM", "NLP", "AI Prediction", "JavaScript", "Responsive Design"],
    loomVideoId: "0d0fc66f292c468c827e2156ccd9185b",
    loomNote: null,
    githubUrl: "https://github.com/saiMahadasa/financial_data_extraction",
  },
] as const;

export const skillsData = [
  "React.js",
  "Next.js",
  "TypeScript",
  "JavaScript (ES6+)",
  "Redux Toolkit",
  "RTK Query",
  "React Hooks",
  "Context API",
  "Tailwind CSS",
  "HTML5",
  "CSS3",
  "WCAG 2.1 Accessibility",
  "Responsive Design",
  "Python",
  "Django",
  "Node.js",
  "FastAPI",
  "REST APIs",
  "GraphQL",
  "JWT Authentication",
  "RBAC",
  "Kafka",
  "LangChain",
  "LangGraph",
  "RAG",
  "Agentic AI",
  "MCP",
  "AWS Bedrock",
  "OpenAI",
  "PostgreSQL",
  "Redis",
  "MySQL",
  "Jest",
  "React Testing Library",
  "pytest",
  "Integration Testing",
  "Unit Testing",
  "Docker",
  "Kubernetes",
  "AWS",
  "GitLab CI/CD",
  "GitHub Actions",
  "Terraform",
  "Git",
  "Structured Logging",
] as const;
