import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { FaReact } from "react-icons/fa";
import { LuGraduationCap } from "react-icons/lu";

export const links = [
  {
    name: "Home",
    hash: "#home",
  },
  {
    name: "About",
    hash: "#about",
  },
  {
    name: "Projects",
    hash: "#projects",
  },
  {
    name: "Skills",
    hash: "#skills",
  },
  {
    name: "Experience",
    hash: "#experience",
  },
  {
    name: "Contact",
    hash: "#contact",
  },
] as const;

export const experiencesData = [
  {
    title: "Bachelor of Engineering, Computer Engineering",
    location: "Kakinada Institute of Engineering and Technology, India",
    description:
      "Earned a Bachelor of Engineering in Computer Engineering with a GPA of 3.58/4.00, establishing a strong foundation in software engineering principles, data structures, and full stack web development.",
    icon: React.createElement(LuGraduationCap),
    date: "Mar 2020",
    level: "Foundation",
    technologies: ["HTML", "CSS", "JavaScript", "Python", "MySQL", "Database Design"],
  },
  {
    title: "Software Developer",
    location: "Multiplier AI Solutions, Hyderabad, India",
    description:
      "Designed a centralized Doctors CRM using Django ORM, React component design, and REST API integration best practices. Built a large-scale healthcare data pipeline using Python and automation scripts to collect, normalize, and enrich records for 70,000+ physicians. Developed Django middleware components for centralized request logging, JWT token validation, and rate limiting. Debugged complex UI issues across high-interaction workflow screens by tracing through React component state and Django REST API responses, improving UI responsiveness by 20%.",
    icon: React.createElement(CgWorkAlt),
    date: "Apr 2020 - Jan 2022",
    level: "Entry Level",
    technologies: [
      "React",
      "JavaScript",
      "Python",
      "Django",
      "REST APIs",
      "PostgreSQL",
      "JWT",
      "Git",
    ],
  },
  {
    title: "Software Developer",
    location: "Rapid Innovation, Noida, India",
    description:
      "Built full-stack features for a financial analytics platform using React.js, TypeScript, Python Django, GraphQL, PostgreSQL, and Redis, delivering 25+ dashboards and report views with drilldown navigation, complex filtering, and aggregation. Improved application performance by 35% by profiling React component trees, applying RTK Query caching, lazy loading, and code splitting. Wrote pytest test suites covering Django views, ORM queries, serializers, and API contract validation. Set up GitHub Actions CI/CD pipelines and AWS infrastructure using Terraform.",
    icon: React.createElement(CgWorkAlt),
    date: "Feb 2022 - Jun 2023",
    level: "Mid Level",
    technologies: [
      "React",
      "TypeScript",
      "Python",
      "Django",
      "GraphQL",
      "Redux Toolkit",
      "PostgreSQL",
      "Redis",
      "Terraform",
      "GitHub Actions",
      "Jest",
      "pytest",
      "Git",
    ],
  },
  {
    title: "Senior Software Developer",
    location: "Perky (Perspective Partners LLC), Fairport, NY",
    description:
      "Designed a multi-agent AI pipeline using LangGraph, FastAPI, OpenAI, and AWS Bedrock with ChromaDB vector embeddings, handling 500+ concurrent users at sub-2s response times. Developed LLM-powered applications using LangChain and AWS Bedrock, including conversational assistants and document Q&A systems. Built responsive, accessible UI using React.js, Next.js and TypeScript with Redux and RTK Query, cutting page load times from 3.5s to 1.2s. Engineered scalable RESTful APIs using Django REST Framework with PostgreSQL, enforcing RBAC and leveraging Django signals for audit logging. Led Agile sprint planning across teams of 8-12 members and mentored 3+ junior developers.",
    icon: React.createElement(FaReact),
    date: "Mar 2024 - Mar 2026",
    level: "Senior",
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Python",
      "Django",
      "FastAPI",
      "Redux Toolkit",
      "PostgreSQL",
      "Redis",
      "LangChain",
      "LangGraph",
      "OpenAI",
      "AWS",
      "Docker",
      "GitLab CI/CD",
    ],
  },
  {
    title: "Master of Science, Computer Science",
    location: "Avila University, Kansas, USA",
    description:
      "Completed graduate study focused on advanced algorithms, machine learning, and AI systems with a strong academic record (GPA 3.63/4.00).",
    icon: React.createElement(LuGraduationCap),
    date: "Dec 2024",
    level: "Advanced",
    technologies: ["Algorithms", "Machine Learning", "AI Systems", "Research"],
  },
] as const;

export const projectsData = [
  {
    title: "HR Management Web Platform",
    description:
      "HR and benefits platform where employees and managers manage leave balances, health benefits, and approval workflows through role-based dashboards. Integrated an LLM-powered policy assistant using LangChain, OpenAI, and ChromaDB RAG pipelines to answer employee queries with contextual accuracy, reducing HR support inquiries significantly. Built for multi-tenant scale with strict RBAC, audit trails, and compliance requirements. Deployed on AWS with a Dockerized CI/CD pipeline across three environments for consistent and reliable releases.",
    tags: [
      "React.js",
      "Next.js",
      "TypeScript",
      "Python",
      "Django",
      "LangChain",
      "OpenAI",
      "ChromaDB",
      "AWS",
      "Docker",
      "PostgreSQL",
      "Redis",
    ],
  },
  {
    title: "Healthcare Management Web Platform",
    description:
      "A secure healthcare platform supporting workflow-driven experiences where users manage dashboards, approvals/status changes, and document-driven processes. On the frontend, built the experience using React.js + TypeScript, combining Redux/Redux Toolkit for shared state. The application integrated with backend services built using Node.js, with collaboration on API design, request validation, and scalable service patterns to keep contracts predictable as business rules evolved. Reliability and performance were supported through Redis session/caching patterns, Docker for environment consistency, and AWS-based deployment practices with New Relic monitoring for tracing and faster incident resolution. Worked with Databricks to support data processing and reporting workflows, enabling efficient handling of large healthcare datasets and improving dashboard performance. Quality improved through Jest tests enforced via GitHub Actions, preventing regressions and ensuring stable releases across environments.",
    tags: [
      "React.js",
      "TypeScript",
      "Node.js",
      "Redux Toolkit",
      "Redis",
      "Docker",
      "AWS",
      "New Relic",
      "Databricks",
      "Jest",
      "GitHub Actions",
    ],
  },
  {
    title: "Financial Analytics Web Application",
    description:
      "Reporting platform for finance and business teams to track metrics, run drilldowns, and generate reports across large datasets in real time. Built 25+ dashboards through a centralized component system, with Redis caching and optimized query pipelines cutting load times from 8 seconds to under 2 seconds under heavy concurrent usage. Deployed on AWS with automated testing and CI/CD pipelines for predictable releases.",
    tags: [
      "React.js",
      "TypeScript",
      "Python",
      "Django",
      "PostgreSQL",
      "Redis",
      "Redux Toolkit",
      "GraphQL",
      "AWS",
      "Terraform",
    ],
  },
  {
    title: "Medicine E-Commerce Platform",
    description:
      "Online medicine selling platform where customers could browse, search, and purchase medicines with real-time inventory tracking and secure checkout. Integrated Stripe for end-to-end payment processing including one-time purchases and prescription-based order flows. Deployed on AWS with S3 for product image storage, RDS for order and inventory data, and EC2 for compute, handling reliable transactions at scale across a growing user base.",
    tags: [
      "React.js",
      "Python",
      "Django",
      "Stripe",
      "AWS",
      "PostgreSQL",
      "REST APIs",
      "S3",
      "EC2",
      "RDS",
    ],
  },
] as const;

export const skillsData = [
  "React.js",
  "Next.js",
  "TypeScript",
  "JavaScript (ES6+)",
  "Redux Toolkit",
  "Zustand",
  "RTK Query",
  "React Hooks",
  "Context API",
  "Tailwind CSS",
  "Sass",
  "HTML5",
  "CSS3",
  "WCAG 2.1 Accessibility",
  "Responsive Design",
  "Python",
  "Django",
  "Node.js",
  "Express.js",
  "FastAPI",
  "REST APIs",
  "GraphQL",
  "Apollo",
  "Terraform",
  "JWT Authentication",
  "RBAC",
  "LangChain",
  "RAG",
  "Agentic AI",
  "LangSmith",
  "LangGraph",
  "OpenAI",
  "Ollama",
  "Hugging Face",
  "ChromaDB",
  "Pinecone",
  "Embeddings",
  "PostgreSQL",
  "MongoDB",
  "MySQL",
  "Redis",
  "SQL Server",
  "Vector DB",
  "Jest",
  "React Testing Library",
  "pytest",
  "GitLab CI/CD",
  "Kubernetes",
  "Helm",
  "Docker",
  "AWS",
  "Git",
  "Postman",
] as const;
